name: 'Build Docker Image'
description: 'Build Docker Image'

inputs:
  service:
    description: for ECR Repository Name
    required: true
  tag:
    description: The tag name
    required: true

runs:
  using: 'composite'
  steps:

    - name: Build Docker Image
      id: image-info
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.service }}
        IMAGE_TAG: ${{ inputs.tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --file docker/Dockerfile
      shell: bash

    - name: Push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.service }}
        #IMAGE_NAME=your-image-name
        TEMP_TAG: ${{ inputs.temp_tag }}
        IMAGE_TAG: ${{ inputs.tag }}
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      shell: bash