name: 'Build Docker Image'
description: 'Build Docker Image'

inputs:
  service:
    description: for ECR Repository Name
    required: true
  dockerfile-path:
    description: dockerfile-absolute-path
    required: true
  new-stg-tag:
    description: The tag name
  latest-stg-tag:
    description: The tag name
  env:
    description: environment (stg, prd)
    required: true
  custom-docker-build-command:
    description: docker-build-command
    default: ''
  custom-docker-image-name:
    description: docker-image-name
    default: ''
  custom-docker-tag:
    description: custom-docker-tag
    default: latest

outputs:
  github-sha-image-exists:
    description: 'Indicates if an image with the same GitHub SHA exists in ECR'
  valid-new-stg-tag:
    description: 'valid new stg tag'

runs:
  using: 'composite'
  steps:

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: Hyunju-Sung/actions-ecr-login-hj@0.0.4

    - name: Valid Image Check
      id: valid-image-check
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ env.ecr-root }}/${{ inputs.env }}/${{ inputs.service }}
        IMAGE_TAG: ${{ inputs.new-stg-tag }}
        CACHE_FILE: /tmp/docker-image-cache.tar.gz
      run: |
        IMAGE_EXISTS=$(aws ecr list-images --repository-name $ECR_REPOSITORY --filter tagStatus=TAGGED --query 'imageIds[?imageTag==`'"$GITHUB_SHA"'`]' --output text)
        if [ -z "$IMAGE_EXISTS" ]; then
          echo "No image found with tag: $GITHUB_SHA"
          echo "::set-output name=github-sha-image-exists::false"
        else
          echo "Image found with tag: $GITHUB_SHA"
          echo "::set-output name=github-sha-image-exists::true"
          echo "valid-new-stg-tag: ${{ inputs.latest-stg-tag }}"
          echo "::set-output name=valid-new-stg-tag::${{ inputs.latest-stg-tag }}"
        fi
      shell: bash

    - name: Build Docker Image and Push to ECR with dockerfile
      if: ${{ inputs.custom-docker-build-command == '' && inputs.custom-docker-image-name == '' && steps.dockerizing-with-dockerfile-prd.outputs.github-sha-image-exists == 'false' }}
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ env.ecr-root }}/${{ inputs.env }}/${{ inputs.service }}
        IMAGE_TAG: ${{ inputs.new-stg-tag }}
        CACHE_FILE: /tmp/docker-image-cache.tar.gz
      run: |
        docker build -q -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA . --file ${{ inputs.dockerfile-path }}
        docker save $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG | gzip > $CACHE_FILE
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
      shell: bash

    - name: Build Docker Image with command and Push to ECR
      if: ${{ inputs.custom-docker-build-command != '' && inputs.custom-docker-image-name != '' && steps.dockerizing-with-dockerfile-prd.outputs.github-sha-image-exists == 'false' }}
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ env.ecr-root }}/${{ inputs.env }}/${{ inputs.service }}
        IMAGE_TAG: ${{ inputs.new-stg-tag }}
        CACHE_FILE: /tmp/docker-image-cache.tar.gz
      run: |
        ${{ inputs.custom-docker-build-command }}
        docker tag ${{ inputs.custom-docker-image-name }}:${{ inputs.custom-docker-tag }} $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker save $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG | gzip > $CACHE_FILE
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
      shell: bash

    - name: Cache Docker layers
      if: ${{ steps.dockerizing-with-dockerfile-prd.outputs.github-sha-image-exists == 'false' }}
      uses: actions/cache@v2
      with:
        path: /tmp/docker-image-cache.tar.gz
        key: ${{ runner.os }}-docker-cache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-cache-