name: 'Build Docker Image'
description: 'Build Docker Image'

inputs:
  service:
    description: for ECR Repository Name
    required: true
  dockerfile:
    description: dockerfile-absolute-path
    required: true
  tag:
    description: The tag name
    required: true
  aws-gh-action-role:
    description: "AWS github action role arn"
    required: true
  workflow-job-name:
    description: "workflow job name calling"
    required: true
  slack_webhook_url:
    description: "slack_webhook_url"
    required: true

runs:
  using: 'composite'
  steps:

    #- uses: actions/checkout@v3
    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: Hyunju-Sung/actions-ecr-login-hj@0.0.4
      with:
        aws-gh-action-role: ${{ inputs.aws-gh-action-role }}
        workflow-job-name: ${{ inputs.workflow-job-name }}
        slack_webhook_url: ${{ inputs.slack_webhook_url }}

    - name: Build and Save Docker Image
      id: image-info
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ inputs.service }}
        IMAGE_TAG: ${{ inputs.tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --file ${{ inputs.dockerfile }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      shell: bash

